--- ### cache use redis
spring.cache.type: redis
spring.cache.redis.time-to-live: 7000s
spring.cache.cache-names: "public:wechat"
spring.data.redis.host: 127.0.0.1
spring.data.redis.port: 6379
spring.data.redis.database: 5
# 密码，建议生产环境开启
spring.data.redis.password:
spring.data.redis.timeout: 10s

spring.data.redis.client-type: lettuce

