server.port: 18180

server.servlet.context-path: /ccs

### thymeleaf
spring.thymeleaf.cache: false
spring.thymeleaf.prefix: classpath:/templates/
#编码
spring.thymeleaf.encoding: UTF-8
#模板后缀
spring.thymeleaf.suffix: .html
#模板
spring.thymeleaf.mode: HTML

--- ## wechat

wechat.api.base-uri: https://api.weixin.qq.com
wechat.api.mini-program.access-token: "/cgi-bin/token?grant_type={grantType}&appid={appid}&secret={secret}"
wechat.api.mini-program.stable-access-token: /cgi-bin/stable_token

